### ISSUE TITLE
repeated CheckSumMismatch errors when running continuosly

### ISSUE THREAD

**Issue by gazzat5** [pimoroni/pms5003-python#3]
Hi, I'm running code to read the sensor continuously (once a second i think), and post to thingspeak every 30s. However the code keeps crashing with the pms5003 library raising the checksummismatch error. It happens roughly every half hour and stops the sensor reading for about half an hour before it goes away from what i can tell. (i've just bypassed it by catching all exceptions in my modified examples/particulates.py

**Comment by Gadgetoid** [comment]
Do you have `dtoverlay=pi3-miniuart-bt` in your `/boot/config.txt`? Serial using the miniUART can cause this, albeit it usually fails to read at all ever.

I'm not entirely sure what else might cause it- if it loses sync then the PMS5003 library will read two bytes (the start of frame) until it matches the right sequence, and then carry on. Taking 30 minutes to resync suggests it's just getting nonsense over serial.

It might be worth modifying the library to print out the `sof` right after it's read or alternatively the next time it fails you could run a simple Python script to poke at what's coming over serial:

```
import serial

bus = serial.Serial('/dev/ttyAMA0', baudrate=9600, timeout=4)
bus.flushInput()
while True:
    value = bus.read(4)
    print(value)
```

**Comment by gazzat5** [comment]
Yes, i have the dtoverlay. tend to run it headless, so ive disabled printing of the values in the terminal so only errors are printed. I'll post back with some more detail.

**Comment by gazzat5** [comment]
exception is: PMS5003 Checksum Mismatch 380 != 6

**Comment by Gadgetoid** [comment]
I've seen other used with serial issues that were fixed by re-seating the PM sensor cable, that may be worth a try first.

If that fails, try running something like the above code that queries serial directly- 

```
import serial

bus = serial.Serial('/dev/ttyAMA0', baudrate=9600, timeout=4)
bus.flushInput()
while True:
    value = bus.read(4)
    if len(value) > 0:
        print(value)
```

Let it run and print out a few dozen lines of values, and paste them here.

**Comment by gazzat5** [comment]
Gadgetoid, is it worth writing a bit of code that will output x number of lines from the serial output when it fails?

Cheers

**Comment by Gadgetoid** [comment]
Did you have any luck with this? It could be a number of things from a tempremental connection, to environmental noise, to temperature, to a faulty pms5003 sensor but it's quite tricky to figure out which. How's your system setup and where is it installed?

**Comment by nophead** [comment]
Mine will run for days and then starts to fail every read. I have to restart my program to get it to work again. I am wondering about the two byte SOF read. Rather than reading two bytes it should read one until it sees the first character and then read the second character. If it always reads two bytes it could get out of step I think.

**Comment by Gadgetoid** [comment]
I could be wrong, but there should be no difference between reading the SOF bytes individually, or reading them together. In either case they should be read from the Pi's receive buffer.

I wonder if it's worth implementing a feature to keep track of CheckSumMismatch and Timeout errors and automatically attempt to reset the PMS5003 if it sees more than two or three in a row. Granted it's probably not helpful to reset the sensor too often since it affects stability and would give periods with no readings. (It takes ~30 seconds for the sensor to stabalise from cold boot due to the fan)

Flushing the serial receive buffer should also work in the case where it's filled- I wonder if something is happening where the serial receive buffer isn't being consumed quickly enough and is being filled by the sensor (once a second) until it's full and causes a short read with garbage data on the end. @nophead How often are you reading the sensor?

Actually, thinking about it @gazzat5 this may very well be your problem since you're only reading the sensor every 30s- so that's ~58 readings every minute of 33 bytes (14 2-byte data values, SOF, frame length and checksum?) that are being left in the buffer.

Now I'm thinking out loud, but maybe the read process should be:

1. Flush input buffer
2. Block waiting for SOF (or timeout)
3. Read and parse data

**Comment by Gadgetoid** [comment]
Well after running this for nearly 2 hours I haven't encountered any checksum mismatch errors. This would seem to disprove my theory. (which was probably on shaky ground to begin with).

**Comment by nophead** [comment]
There is a difference reading the SOF bytes individually because you should keep reading one byte until you hit the first SOF character and then read a second byte to check for the second SOF character. If either comparison fails you go to the waiting for first SOF state.

As it stands if you get an extra or a missing character then reading two characters will never align with the two SOF characters.

**Comment by Gadgetoid** [comment]
@nophead yep, came here to say I was wrong for exactly that reason. Since I can't seem to hit a UART buffer overflow, I'm going to modify the library accordingly and read the SOF bytes individually.

**Comment by gazzat5** [comment]
Thanks guys, i have updated my code with the exception of my exception handling, which is now giving me errors 🙄 

`except Exception as e:` syntax error...DOH!

Will let you guys know if this resolves the error. Now without exception handling i guess my script will die fairly quickly if there's an error in the serial stream/the timeout occurs again.

**Comment by deckardstp** [comment]
Any heads up on this topic?

**Comment by Gadgetoid** [comment]
To my knowledge this problem shouldn't be happening anymore, but I suspect that if it does it's related to the "burst" mode of the sensor and we may require a threaded read to ensure that values sent greater than 1/sec are read off the buffer before they overflow it.

See: https://github.com/pimoroni/pms5003-python/issues/6

**Comment by gazzat5** [comment]
I'll have to retest this on my revised pi install as I've had to rebuild
it...

**Comment by deckardstp** [comment]
I cought the error in the meantime with an exception. It looks good now.

**Comment by gazzat5** [comment]
Can you post/issue the code with the exception handling please? Would be
useful...I think my code I just gave a general exception handling and moved
on...would be good to see if you did something more specific.

**Comment by deckardstp** [comment]
I let it run in a docker container. If you're interested I can provide you a public link to the gitlab repo.

```
import time
import datetime
from pms5003 import PMS5003, ReadTimeoutError, ChecksumMismatchError, SerialTimeoutError
import mysql.connector
from mysql.connector import Error
from mysql.connector import errorcode

# pms5003 data from air quality sensor
pms5003_instance = PMS5003()
time.sleep(1.0)

def get_pms_sensor_data():
    pms_data = pms5003_instance.read()
    return {
        "pm_ug_per_m3_1_0": pms_data.pm_ug_per_m3(1.0),
        "pm_ug_per_m3_2_5": pms_data.pm_ug_per_m3(2.5),
        "pm_ug_per_m3_10": pms_data.pm_ug_per_m3(10),
        "pm_per_dl_0_3": pms_data.pm_per_1l_air(0.3),
        "pm_per_dl_0_5": pms_data.pm_per_1l_air(0.5),
        "pm_per_dl_1_0": pms_data.pm_per_1l_air(1.0),
        "pm_per_dl_2_5": pms_data.pm_per_1l_air(2.5),
        "pm_per_dl_5_0": pms_data.pm_per_1l_air(5.0),
        "pm_per_dl_10_0": pms_data.pm_per_1l_air(10.0)
    }


def store_sensor_data(data):
    try:
        connection = mysql.connector.connect(host='',
                                         database='sensor_data',
                                         user='sensoruser',
                                         password='')
        now = datetime.datetime.utcnow()
        print(now)
        val1 = data['pm_ug_per_m3_1_0']
        val2 = data['pm_ug_per_m3_2_5']
        val3 = data['pm_ug_per_m3_10']
        val4 = data['pm_per_dl_0_3']
        val5 = data['pm_per_dl_0_5']
        val6 = data['pm_per_dl_1_0']
        val7 = data['pm_per_dl_2_5']
        val8 = data['pm_per_dl_5_0']
        val9 = data['pm_per_dl_10_0']
        mysql_insert_query = """INSERT INTO pms5003(time, pm_ug_per_m3_1_0, pm_ug_per_m3_2_5, pm_ug_per_m3_10, pm_per_dl_0_3, pm_per_dl_0_5, pm_per_dl_1_0,pm_per_dl_2_5, pm_per_dl_5_0, pm_per_dl_10_0) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"""
        cursor = connection.cursor()
        cursor.execute(mysql_insert_query, (now.strftime('%Y-%m-%d %H:%M:%S'), val1, val2, val3, val4, val5, val6, val7, val8, val9))
        connection.commit()
        print(cursor.rowcount, "Record inserted successfuly")
        cursor.close()
        connection.is_connected()
        connection.close()
        print("mysql connection is closed")

    except mysql.connector.Error as error:
        print("Failed to insert record {}".format(error))

try:
    while True:
        try:
            values = get_pms_sensor_data()
            print(values)
            write_data = store_sensor_data(values)
        except ReadTimeoutError:
            pms5003 = PMS5003()
            pass
        except ChecksumMismatchError:
            pms5003 = PMS5003()
            pass
        except SerialTimeoutError:
            pms5003 = PMS5003()
            pass
except KeyboardInterrupt:
    pass
```

**Comment by pietrouk** [comment]
I'm bumping into the same issue. I'm using enviroplus-exporter to collect the outputs into prometheus and then visualise them in grafana.

Full error I get is:

```
enviroplus-exporter.service - Enviroplus-exporter service
   Loaded: loaded (/etc/systemd/system/enviroplus-exporter.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-06-07 11:50:07 BST; 6h ago
  Process: 12832 ExecStart=/usr/bin/python /usr/src/enviroplus_exporter/enviroplus_exporter.py --bind=0.0.0.0 --port=8000 (code=exited, status=1/FAILURE)
 Main PID: 12832 (code=exited, status=1/FAILURE)

Jun 07 11:50:07 raspberrypi python[12832]: Traceback (most recent call last):
Jun 07 11:50:07 raspberrypi python[12832]:   File "/usr/src/enviroplus_exporter/enviroplus_exporter.py", line 145, in <module>
Jun 07 11:50:07 raspberrypi python[12832]:     get_particulates()
Jun 07 11:50:07 raspberrypi python[12832]:   File "/usr/src/enviroplus_exporter/enviroplus_exporter.py", line 113, in get_particulates
Jun 07 11:50:07 raspberrypi python[12832]:     pms_data = pms5003.read()
Jun 07 11:50:07 raspberrypi python[12832]:   File "/usr/local/lib/python2.7/dist-packages/pms5003-0.0.5-py2.7.egg/pms5003/__init__.py", line 155, in read
Jun 07 11:50:07 raspberrypi python[12832]:     raise ChecksumMismatchError("PMS5003 Checksum Mismatch {} != {}".format(checksum, data.checksum))
Jun 07 11:50:07 raspberrypi python[12832]: pms5003.ChecksumMismatchError: PMS5003 Checksum Mismatch 902 != 0
Jun 07 11:50:07 raspberrypi systemd[1]: enviroplus-exporter.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 11:50:07 raspberrypi systemd[1]: enviroplus-exporter.service: Failed with result 'exit-code'.

```
If I then restart the service, everything starts working again immediately.
After a few hours though the problem will represent itself.

**Comment by Gadgetoid** [comment]
@pietrouk you could try flushing the serial buffer and resetting the sensor when this happens, though that would require modifying the EnviroPlus Exporter example:

https://github.com/tijmenvandenbrink/enviroplus_exporter/blob/0a52f817268a023ecb622b2f31f9b2b38490e664/enviroplus_exporter.py#L112-L121

Right now it looks like it handles a `pmsReadTimeoutError`, but doesn't attempt any recovery.

Might be worth logging a warning, trying again or calling `pms5003.reset()` in the case of a checksum error, though I appreciate resetting the device can mess with the stability of the sensor.

If you change this line: https://github.com/tijmenvandenbrink/enviroplus_exporter/blob/0a52f817268a023ecb622b2f31f9b2b38490e664/enviroplus_exporter.py#L11

To something like:

```python
from pms5003 import PMS5003, ReadTimeoutError as pmsReadTimeoutError, ChecksumMismatchError as pmsChecksumMismatchError 
```

And then this line: https://github.com/tijmenvandenbrink/enviroplus_exporter/blob/0a52f817268a023ecb622b2f31f9b2b38490e664/enviroplus_exporter.py#L116

To:

```python
except pmsReadTimeoutError, pmsChecksumMismatchError:
```

Then it will at least fail with a log warning when the sensor fails to read, rather than bailing out the script altogether.

Also `enviroplus_exporter.py` seems to run with an unbounded `while True` loop with no delay, so it may be attempting to read the PMS5003 much faster than the normal 1sec update interval. Though I would expect a short read to fail with a SerialTimeoutError "Invalid frame length", seen here: https://github.com/pimoroni/pms5003-python/blob/ebdafc2c9ad07eafc48ec49dd63e69e91831524e/library/pms5003/__init__.py#L148

**Comment by pietrouk** [comment]
Thank you @Gadgetoid, super helpful. Made the changes you suggest and added a 1 second wait to the while loop.

**Comment by AB-H** [comment]
Two cents proposal: if you have another process requiring PMS5003 it creates conflict. For example if you add on crontab -e something like "@reboot python3 luftdaten.py" You cannot use python3 all-in-one.py after

**Comment by gazzat5** [comment]
Thats because only one process can use the serial port at a time. To get
around it you'd need to create a pair of virtual serial ports that
duplicate the content of the hardware port the PMS5003 uses.
